### ISSUE TITLE
Error: TypeError: Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by simenandre** [bjerkio/kopier#7]
Workflow this happends on:

```yaml
on:
  push:
    branches: [dockerx]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bjerkio/kopier@main
        with:
          repos: |
            indivorg/service-user
          github-token: ${{ secrets.GH_PRIVATE_TOKEN }}
```
